# Generated by Django 4.2 on 2024-12-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neervaani_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('land_size', models.FloatField()),
                ('land_unit', models.CharField(choices=[('katha', 'Katha'), ('acres', 'Acres'), ('bigha', 'Bigha')], max_length=10)),
                ('irrigation_method', models.CharField(choices=[('flood', 'Flood'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('surface', 'Surface'), ('center_pivot', 'Center Pivot')], max_length=50)),
                ('rainfall_mm', models.FloatField()),
                ('irrigation_cycles', models.IntegerField()),
                ('crop_yield', models.FloatField()),
                ('fertilizer_use', models.FloatField()),
                ('growing_season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], max_length=10)),
                ('avg_temperature', models.FloatField()),
                ('water_footprint', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neervaani_app.user')),
            ],
        ),
    ]
